/* eslint-disable import/prefer-default-export */

export const FIND_ORDER = 'FIND_ORDER';
export const PLACE_ORDER = 'PLACE_ORDER';
export const HANDLE_ERROR_ON_ORDER = 'HANDLE_ERROR_ON_ORDER';
export const RESET_ORDER = 'RESET_ORDER';
export const RESET_ERROR = 'RESET_ERROR';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const APPLY_DISCOUNT_ON_PRODUCT = 'APPLY_DISCOUNT_ON_PRODUCT';
export const VIEW_PRODUCT = 'VIEW_PRODUCT';
export const SELECT_PRODUCT_COLOR = 'SELECT_PRODUCT_COLOR';
export const SELECT_PRODUCT_SIZE = 'SELECT_PRODUCT_SIZE';
export const SELECT_PRODUCT_QUANTITY = 'SELECT_PRODUCT_QUANTITY';
export const SET_COLLECTION = 'SET_COLLECTION';
export const GET_COLLECTIONS = 'GET_COLLECTIONS';

export const GET_WOMEN = 'GET_WOMEN';
export const VIEW_WOMAN = 'VIEW_WOMAN';

export const VERIFY_COUPON = 'VERIFY_COUPON';
export const HANDLE_INVALID_COUPON = 'HANDLE_INVALID_COUPON';
export const RESET_UNUSED_COUPON = 'RESET_UNUSED_COUPON';
